# Empty Cells
Empty cells can potentially give you a wrong result when you analyze data.

## Remove Rows
One way to deal with empty cells is to remove rows that contain empty cells.

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.

In [1]:
import pandas as pd

In [20]:
import numpy as np
# Método 2: Criando manualmente com dicionário
data = {
    'Duration': [60, 60, 60, 45, 45, 60, 60, 450, 30, 60, 60, 60, 60, 60, 60, 60, 60, 60, 45, 60, 45, 60, 45, 60, 45, 60, 60, 60, 60, 60, 60, 60],
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03', '2020/12/04', '2020/12/05', '2020/12/06', '2020/12/07', '2020/12/08', '2020/12/09', '2020/12/10', '2020/12/11', '2020/12/12', '2020/12/12', '2020/12/13', '2020/12/14', '2020/12/15', '2020/12/16', '2020/12/17', '2020/12/18', '2020/12/19', '2020/12/20', '2020/12/21', np.nan, '2020/12/23', '2020/12/24', '2020/12/25', 2020/12/26, '2020/12/27', '2020/12/28', '2020/12/29', '2020/12/30', '2020/12/31'],
    'Pulse': [110, 117, 103, 109, 117, 102, 110, 104, 109, 98, 103, 100, 100, 106, 104, 98, 98, 100, 90, 103, 97, 108, 100, 130, 105, 102, 100, 92, 103, 100, 102, 92],
    'Maxpulse': [130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 120, 128, 132, 123, 120, 120, 112, 123, 125, 131, 119, 101, 132, 126, 120, 118, 132, 132, 129, 115],
    'Calories': [409.1, 479.0, 340.0, 282.4, 406.0, 300.0, 374.0, 253.3, 195.1, 269.0, 329.3, 250.7, 250.7, 345.3, 379.3, 275.0, 215.2, 300.0, np.nan, 323.0, 243.0, 364.2, 282.0, 300.0, 246.0, 334.5, 250.0, 241.0, np.nan, 280.0, 380.3, 243.0]
}

df = pd.DataFrame(data)

print("\n" + "="*50) # Separador visual
print("DataFrame criado manualmente:")
# print(df)
print(df)  # Exemplo de célula vazia

df.to_csv('dataForDC.csv', index=False)

==================================================
DataFrame criado manualmente:
    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60    6.474359    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [21]:
df = pd.read_csv('dataForDC.csv')

In [27]:
# Novo df sem células vazias. Remove todas as linhas que possuem ao menos uma célula vazia (NaN).
# Por padrão, o método dropna() retorna um novo DataFrame, e não altera o original.
new_df = df.dropna()

print(new_df.to_string())

new_df

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

In [28]:
# Caso queira salvar o novo DataFrame com alterações do dropna usamos implace = True
# df = pd.read_csv('dataForDC.csv')

df.dropna(inplace = True)

print(df.to_string())

# Nesse caso não retorna um novo DataFrame, mas altera o original.

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

## Replace Empty Values
Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:

In [ ]:
# Preenchendo uam celula com com o numero 130

df = pd.read_csv('dataForDC.csv')

df_preenchdo130 = df.fillna(130)

df_preenchdo130 # Onde era NaN agora é 130

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
18        45          2020/12/18     90       112     130.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
22        45                 130    100       119     282.0
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
28        60          2020/12/28    103       132     130.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

In [32]:
# Preenchendo uam celula com com o numero 130

# Tb pode ser usado inplace = True

df = pd.read_csv('dataForDC.csv')

df.fillna(130, inplace = True)

df # Onde era NaN agora é 130

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
18        45          2020/12/18     90       112     130.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
22        45                 130    100       119     282.0
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
28        60          2020/12/28    103       132     130.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

## Replace Only For Specified Columns
The example above replaces all empty cells in the whole Data Frame.

To only replace empty values for one column, specify the column name for the DataFrame:

In [35]:
df = pd.read_csv('dataForDC.csv')

df.fillna({"Calories": 130}, inplace=True) # Substitui apenas em colunas especificas. Nesse caso subistituindo os NULL Values por 130.

df

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130     409.1
1         60          2020/12/02    117       145     479.0
2         60          2020/12/03    103       135     340.0
3         45          2020/12/04    109       175     282.4
4         45          2020/12/05    117       148     406.0
5         60          2020/12/06    102       127     300.0
6         60          2020/12/07    110       136     374.0
7        450          2020/12/08    104       134     253.3
8         30          2020/12/09    109       133     195.1
9         60          2020/12/10     98       124     269.0
10        60          2020/12/11    103       147     329.3
11        60          2020/12/12    100       120     250.7
12        60          2020/12/12    100       120     250.7
13        60          2020/12/13    106       128     345.3
14        60          2020/12/14    104       132     379.3
15        60          2020/12/15     98       123     275.0
16        60          2020/12/16     98       120     215.2
17        60          2020/12/17    100       120     300.0
18        45          2020/12/18     90       112     130.0
19        60          2020/12/19    103       123     323.0
20        45          2020/12/20     97       125     243.0
21        60          2020/12/21    108       131     364.2
22        45                 NaN    100       119     282.0
23        60          2020/12/23    130       101     300.0
24        45          2020/12/24    105       132     246.0
25        60          2020/12/25    102       126     334.5
26        60  6.4743589743589745    100       120     250.0
27        60          2020/12/27     92       118     241.0
28        60          2020/12/28    103       132     130.0
29        60          2020/12/29    100       132     280.0
30        60          2020/12/30    102       129     380.3
31        60          2020/12/31     92       115     243.0

## Replace Using Mean, Median, or Mode
A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column:

In [38]:
df = pd.read_csv('dataForDC.csv')

x = df['Calories'].mean() #calcula a média da coluna
# O mesmo serve para .median() que pega o valor do meio e .mode() o valor que aparece com mais frequencia.

df.fillna({'Calories': x}, inplace=True) # substitui os NULL pela média da coluna

df

    Duration                Date  Pulse  Maxpulse  Calories
0         60          2020/12/01    110       130    409.10
1         60          2020/12/02    117       145    479.00
2         60          2020/12/03    103       135    340.00
3         45          2020/12/04    109       175    282.40
4         45          2020/12/05    117       148    406.00
5         60          2020/12/06    102       127    300.00
6         60          2020/12/07    110       136    374.00
7        450          2020/12/08    104       134    253.30
8         30          2020/12/09    109       133    195.10
9         60          2020/12/10     98       124    269.00
10        60          2020/12/11    103       147    329.30
11        60          2020/12/12    100       120    250.70
12        60          2020/12/12    100       120    250.70
13        60          2020/12/13    106       128    345.30
14        60          2020/12/14    104       132    379.30
15        60          2020/12/15     98       123    275.00
16        60          2020/12/16     98       120    215.20
17        60          2020/12/17    100       120    300.00
18        45          2020/12/18     90       112    304.68
19        60          2020/12/19    103       123    323.00
20        45          2020/12/20     97       125    243.00
21        60          2020/12/21    108       131    364.20
22        45                 NaN    100       119    282.00
23        60          2020/12/23    130       101    300.00
24        45          2020/12/24    105       132    246.00
25        60          2020/12/25    102       126    334.50
26        60  6.4743589743589745    100       120    250.00
27        60          2020/12/27     92       118    241.00
28        60          2020/12/28    103       132    304.68
29        60          2020/12/29    100       132    280.00
30        60          2020/12/30    102       129    380.30
31        60          2020/12/31     92       115    243.00